version: '3.1'
services:
  db:
    image: mysql:5.6.51
    platform: linux/x86_64
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    volumes:
      - db_volume:/var/mysql
  app:
    build:
      context: ../docker
      dockerfile: Dockerfile_App
    command: java -jar /app.jar
    container_name: spring-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:niceDB
      SERVER_PORT: 8081
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/niceDB?autoReconnect=true&useSSL=false
    volumes:
      - /temp
    depends_on:
      - db
  jenkins:
    build:
      context: ../docker/
      dockerfile: Dockerfile_Jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    restart: always
volumes:
  db_volume: